apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: acme-crt-chronograf
spec:
  secretName: acme-crt-secret-chronograf
  dnsNames:
    - chronograf.kerkoleng.co
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - chronograf.kerkoleng.co
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
